name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show repo
        run: |
          echo "unity-client CI placeholder — repo: "
      - name: Success
        run: echo "CI success"
